version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/github_action
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: /scripts/prepare_permissions.sh
      timeout: 60
      runas: root
      
  ApplicationStart:
    - location: /scripts/gh_deploy.sh
      timeout: 60
      runas: ubuntu
      
