name: Deploy to Beanstalk
on:
  push:
    branches:
      - docker_main

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Make application.properties
        run: |
          touch ./src/main/resources/application.properties
          echo "${{ secrets.APP_DOCKER }}" s> ./src/main/resources/application.properties
          cat ./src/main/resources/application.properties

      - name: Setup Gradle Wrapper
        run: gradle wrapper --gradle-version 8.5
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gyungtaek/gyungtaek:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_SSH }}
          script: |
            sudo service docker start
            docker pull gyungtaek/gyungtaek:latest
            docker run -d -p 1234:1234 gyungtaek/gyungtaek:latest